### ISSUE TITLE
Interface change for Trajectory Builder

### ISSUE THREAD

**Issue by Fluci** [itko/mousetrack#9]
I'm working on a draft for the Pipeline and need your oppinion.

I've noted that we've defined the `TrajectoryBuilder` interface in a very monolithic way: it takes a cluster chain and returns a Trajectory.
But on the other hand side we've defined `Matching` incrementally, it just tells us, where to append the clusters.

I would like to change the interface from:

``` C++
virtual Trajectory operator()(const ClusterChain& chain) const = 0;
```

to: 

``` C++
virtual Eigen::Vector3d operator()(const std::shared_ptr<const ClusterDescriptor> descriptor, const Cluster& cluster) const = 0;
```

This means, the trajectory builder is no longer able to reason about an entire cluster chain, only about the last cluster and its descriptor. 

There might be operations, where we want to take the entire trajectory into account at a later point (smoothing, outlier removal etc.). But I claim, most of those operations are also well implemented with an incremental approach (maybe with a sliding window in form of cached data).

One issue I still have, is the name. But I couldn't think of anything fitting. Maybe ControlPointFactory? Sound also stupid ...

Open for your thoughts.

PS: I'll create a pull request with a draft.

**Comment by Fluci** [comment]
See pull request #10

**Comment by itko** [comment]
What exactly is the issue with the way it os now? Do you have a use case
where it is not sufficient?

**Comment by Fluci** [comment]
First use case:

we have an interactive application that displays a trajectory as it is calculated.

If we use the old interface, we need to store all the clusters and cluster descriptors of a chain. Each time, we update the trajectory, we need to go through all clusters and calculate the centers.

If we use the new interface, we can calculate incremental change, i.e. for each new cluster, we only need to calculate its center of gravity.

Difference:

- We save memory (we can delete clusters and their descriptors, as soon as we no longer need them).
- Updates are faster (we remove redundant computations of the cog's)

Second use case:

We want to write our result to a file.

If we use the old interface, we need to wait until the entire batch is processed and then write it out.

If we use the new interface, we can write results as soon as they are available. 

Difference:

- Robustness: If the application crashes for some reason, only the last frames are lost. Work can continue where it crashed.

**Comment by luhug** [comment]
I hope I understand this correctly, so this basically just computes the center of gravity for the cluster? If we use CoG for cluster descriptors, is this basically just projecting the 4D CoG to 3D? If so, this is indeed a better approach.

**Comment by Fluci** [comment]
It does not change anything on the implementation apart from moving the loop (which iterates over the chain elements) outside the method.
